### ISSUE TITLE
Human detections: lots of false positives

### ISSUE THREAD

**Issue by svddries** [tue-robotics/ed_perception#13]
Sometimes, even a human is detected in the edge of table top. Is size taken into account?

**Comment by LFBFerreira** [comment]
Yes size is taken into account. Sometimes i get the opposite, big entities being considered as small known objects. Sometimes i'm not sure if the entities are being processed every new frame, they seem to hold previous information that doesn't get updated, so if the first time the robot saw an object and it was big, it will continue to be big even tough the segmentation shows otherwise a few frames later.

I'll continue investigating this.

**Comment by LFBFerreira** [comment]
Hopefully this was fixed in commit e403ecc6e805a5e1d716e923816982f4cd2f8791 . If a type could not be determined, the type aggregator writes "unknown" instead of a empty string, which was causing the visualization not to update the type in the debug window. Or did you also see false positives in RViz?
